# Generated by Django 2.0.4 on 2018-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_with_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thedatabase',
            name='age',
            field=models.IntegerField(),
        ),
    ]
